service: birthday-reminder-mailer
frameworkVersion: "2"

custom:
  defaultStage: prod
  environment: ${file(env.yml):default}

provider:
  name: aws
  runtime: nodejs16.x
  lambdaHashingVersion: 20201221
  stage: prod
  region: ap-south-1
  environment:
    DB_URI: ${self.custom.environment.DB_URI}
    DB_NAME: ${self.custom.environment.DB_NAME}
    EMAIL: ${self:custom.environment.EMAIL}
    PASSWORD: ${self:custom.environment.PASSWORD}

functions:
  sendReminderEmail:
    handler: src/index.sendReminderEmail
    events:
      - schedule: cron(0 0 * * *)
